title: De manager zonder stress
email: info@managerzonderstress.nl
button_text: Ik geef extra informatie
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
managers_dir: managers

# backdrop: "/Tijdsurfendemanager.jpg"
backdrop: /managerasgoalkeeper.jpg

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    sass_dir: style
